# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
before_all do
  # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
end

#Test Lanes
desc "Runs tests and builds example for the given environment"
desc "####Options"
desc " * **`configuration`**: The build configuration to use. (`BK_CONFIGURATION`)"
desc ""
lane :ci_commit do |options|
  if options[:configuration]
    configuration = options[:configuration]
  elsif ENV["BK_CONFIGURATION"]
    configuration = ENV["BK_CONFIGURATION"]
  else
    configuration = "Release"
  end
  
  if options[:scheme]
    appscheme = options[:scheme]
  elsif ENV["BK_SCHEME"]
    appscheme = ENV["BK_SCHEME"]
  else
    # appscheme = "BKApp"
  end
  if ENV["BK_CARTHAGE"]
    carthage(use_binaries: false,verbose: ENV["BK_CARTHAGE_LOG"] || false)
  end
  run_tests(scheme: appscheme)
end

desc "framework_release_candidate "
desc "####Options"
desc " * **`version`** (required): The new version of the framework"
lane :framework_release_candidate do |options|
    if !options[:version]
        raise "No version specified!".red
    end
    version_bump_podspec(
      version_number: options[:version]
    )
    pod_lib_lint(allow_warnings: true)
end

desc "prepare_framework_release "
desc "####Options"
desc " * **`version`** (required): The new version of the framework"
lane :prepare_framework_release do |options|
    if !options[:version]
        raise "No version specified!".red
    end
    version_bump_podspec(
      version_number: options[:version]
    )
    pod_lib_lint(allow_warnings: true)
end

desc "framework_release "
desc "####Options"
desc " * **`version`** (required): The new version of the framework"
lane :framework_release do |options|
    if options[:tag_name]
        tag_name = options[:tag_name]
    elsif ENV["CI_COMMIT_TAG"]
        tag_name = ENV['CI_COMMIT_TAG']
    else
        raise "provided your tag.!".red
    end
    version_bump_podspec(
      version_number: tag_name
    )
    pod_lib_lint(allow_warnings: true)
    pod_push(allow_warnings: true)
end

after_all do |lane|
  # This block is called, only if the executed lane was successful
  
  # slack(
  #   message: "Successfully deployed new App Update."
  # )
end

error do |lane, exception|
  # slack(
  #   message: exception.message,
  #   success: false
  # )
end
